language: go

script:
  - hugo --baseUrl=dennismao.github.io

after_script:
  - cd ./public
  - git init
  - git config user.name "dennismao"
  - git config user.email "raymond_2008@yahoo.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GIT_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/dennismao/dennismao.github.io.git
