language: go

go:
  - 1.9.2

install:
  - go get github.com/spf13/hugo

script:
  - hugo

after_script:
  - cd ./public
  - cp ../CNAME CNAME
  - git init
  - git config user.name "dennismao"
  - git config user.email "raymond_2008@yahoo.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_REF}@${GIT_TOKEN}" master:master
  
branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/dennismao/dennismao.github.io.git
