baseurl = "http://dennismao.github.io/"
languageCode = "en-us"
title = "后端小筑"
theme= "hugo-theme-geppaku"
googleAnalytics = ""
disqusShortname = ""

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Razil"
    avatar = "https://gss0.baidu.com/9vo3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/5d6034a85edf8db10237879c0e23dd54564e7429.jpg"
    description = "语言:C/C++/Go"
    lang = "语言:C/C++/Go "
    tar = "技术方向:应用后端、分布式"

    # Please set account ids
    # This is Optional values
    # twitter  = "your twitter id"
    # linkedin = "your linkedin id"
    github   = "github.com/dennismao"
    #tumblr   = "your tumblr id"


[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
         twitter  = false
         facebook = false
         tumblr   = false
        # hatena   = true # hatena is Japanese social media
        # google   = true
        # pocket   = true
        # Please set id when you want to display facebook
        facebookAppId = "your app id"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        #sidebar = "adsense/sidebar.html"
        #content = "adsense/content.html"
